apiVersion: v1
kind: Service
metadata:
  name: te-data-generator-backend
  namespace: korea
  labels:
    app: te-data-generator
    component: backend
    owner/name: korea
    owner/purpose: develop
  annotations:
    description: "This service is used for korea team"
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: te-data-generator
    component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: te-data-generator-frontend
  namespace: korea
  labels:
    app: te-data-generator
    component: frontend
    owner/name: korea
    owner/purpose: develop
  annotations:
    description: "This service is used for korea team"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: te-data-generator
    component: frontend
